<a href="https://colab.research.google.com/github/sujitha-source/Full-stack-development-python-/blob/main/numpy(5/5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
s=[5,10,15,20]
type(s)
x=np.array(s)
print(x)
np.max(s)
print(max(s))
np.min(s)
print(min(s))
np.mean(s)
print(np.mean(s))

[ 5 10 15 20]
20
5
12.5


In [22]:
import numpy as np
x=np.random.randint(1,10,15)
print(x)
a=np.sort(x)
print(a)


[1 1 2 7 6 4 3 6 4 8 9 6 1 4 4]
[1 1 1 2 3 4 4 4 4 6 6 6 7 8 9]


In [36]:
import numpy as np
x=np.arange(1,26).reshape(5,5)
print(x)





[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
